import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import { getDemoConfig } from '../modules/demo/config.js';
import { getDemoAiProviders, getDemoAiTimeoutMs } from '../config/ai.js';
import { assertProdConfig } from '../config/assertProdConfig.js';

/**
 * Task B7: the public demo reaches the production deployments, and ships OFF.
 *
 * The code reads DEMO_* and AI_DEMO_* from the environment, so a deployment file that does not forward a variable makes
 * it impossible to set. These tests read render.yaml and docker-compose.prod.yml as YAML and check, against the variables
 * the code really reads, that (1) every one is forwarded, (2) the demo is off unless the owner turns it on, (3) the
 * secret has no value in the repository, (4) an EMPTY value (what docker compose passes for an unset variable) keeps
 * every default of the backend instead of overriding it.
 */

const ROOT = path.resolve(__dirname, '../../../..');
const read = (rel: string): string => fs.readFileSync(path.join(ROOT, rel), 'utf8');

/** Every variable of the demo that the backend reads, taken from the source so a new one cannot be forgotten here. */
const DEMO_VARS = [...new Set(read('packages/backend/src/modules/demo/config.ts').match(/(?<![A-Z0-9_])DEMO_[A-Z0-9_]*[A-Z0-9]/g) ?? [])].sort();
const AI_DEMO_VARS = [...new Set(read('packages/backend/src/config/ai.ts').match(/(?<![A-Z0-9_])AI_DEMO_[A-Z0-9_]*[A-Z0-9]/g) ?? [])].sort();
const ALL_VARS = [...DEMO_VARS, ...AI_DEMO_VARS];

interface RenderVar {
  key: string;
  value?: string | number | boolean;
  sync?: boolean;
  generateValue?: boolean;
}
const render = yaml.load(read('render.yaml')) as { services: Array<{ name: string; envVars: RenderVar[] }> };
const renderBackend = render.services.find((s) => s.name === 'mockia-backend')!.envVars;
const compose = yaml.load(read('docker-compose.prod.yml')) as { services: Record<string, { environment?: Record<string, string> }> };
const composeEnv = compose.services.backend.environment ?? {};

describe('the list of demo variables is what we think it is', () => {
  it('reads the 7 DEMO_* and the 2 AI_DEMO_* variables', () => {
    expect(DEMO_VARS).toEqual(
      ['DEMO_DAILY_GENERATIONS', 'DEMO_ENABLED', 'DEMO_HMAC_SECRET', 'DEMO_MAX_CONCURRENT', 'DEMO_MOCK_TTL_MINUTES', 'DEMO_PER_IP_GENERATIONS', 'DEMO_PER_NET_GENERATIONS', 'DEMO_POW_BITS'].sort(),
    );
    expect(AI_DEMO_VARS).toEqual(['AI_DEMO_PROVIDERS', 'AI_DEMO_TIMEOUT_MS']);
  });
});

describe('render.yaml', () => {
  const find = (key: string) => renderBackend.find((v) => v.key === key);

  it.each(ALL_VARS)('forwards %s to the backend', (key) => {
    expect(find(key)).toBeDefined();
  });

  it('does not forward them to the static frontend (nothing of the demo is secret-bearing there)', () => {
    const frontend = render.services.find((s) => s.name === 'mockia-frontend')!;
    for (const key of ALL_VARS) expect(frontend.envVars.find((v) => v.key === key)).toBeUndefined();
  });

  it('ships the demo OFF: DEMO_ENABLED is never set to a value in the file (the dashboard decides) and certainly not to true', () => {
    const enabled = find('DEMO_ENABLED')!;
    expect(enabled).toEqual({ key: 'DEMO_ENABLED', sync: false });
    expect(JSON.stringify(renderBackend)).not.toMatch(/DEMO_ENABLED[^}]*"value":\s*"?(true|1|yes|on)/i);
  });

  it('gives the secret no value in the repository: generated by the platform (a 256-bit random string, longer than the 32 characters the backend demands)', () => {
    expect(find('DEMO_HMAC_SECRET')).toEqual({ key: 'DEMO_HMAC_SECRET', generateValue: true });
  });

  it('leaves the limits and the AI settings of the demo to the owner (empty keeps the code defaults)', () => {
    for (const key of ALL_VARS.filter((k) => k !== 'DEMO_ENABLED' && k !== 'DEMO_HMAC_SECRET')) {
      expect(find(key)).toEqual({ key, sync: false });
    }
  });

  it('has each variable once', () => {
    const keys = renderBackend.map((v) => v.key);
    expect(new Set(keys).size).toBe(keys.length);
  });

  it('keeps TRUST_PROXY=2 (the demo identifies visitors by req.ip) and does not make the demo depend on a new variable to boot', () => {
    expect(find('TRUST_PROXY')).toEqual({ key: 'TRUST_PROXY', value: 2 });
  });
});

describe('docker-compose.prod.yml', () => {
  it.each(ALL_VARS)('forwards %s to the backend as ${VAR:-...} (never required: a deployment without the demo must still start)', (key) => {
    expect(composeEnv[key]).toBeDefined();
    expect(composeEnv[key]).toMatch(new RegExp(`^\\$\\{${key}:-[^}]*\\}$`));
    expect(composeEnv[key]).not.toContain(':?');
  });

  it('ships the demo OFF unless DEMO_ENABLED is set', () => {
    expect(composeEnv.DEMO_ENABLED).toBe('${DEMO_ENABLED:-false}');
  });

  it('has no secret in the file: DEMO_HMAC_SECRET defaults to empty', () => {
    expect(composeEnv.DEMO_HMAC_SECRET).toBe('${DEMO_HMAC_SECRET:-}');
  });

  it('every other demo variable defaults to empty, so the code defaults apply', () => {
    for (const key of ALL_VARS.filter((k) => k !== 'DEMO_ENABLED')) expect(composeEnv[key]).toBe(`\${${key}:-}`);
  });

  it('does not forward them to the frontend or mongo containers', () => {
    for (const name of ['frontend', 'mongo']) {
      const env = compose.services[name]?.environment ?? {};
      for (const key of ALL_VARS) expect(env[key]).toBeUndefined();
    }
  });
});

describe('what the deployments hand to the backend when the owner sets nothing', () => {
  const emptyDemo = Object.fromEntries(ALL_VARS.map((k) => [k, '']));
  const composeDefault = { ...emptyDemo, DEMO_ENABLED: 'false' };

  it('the code defaults survive empty strings (docker compose passes an unset ${VAR:-} as "")', () => {
    expect(getDemoConfig(emptyDemo as NodeJS.ProcessEnv)).toEqual(getDemoConfig({} as NodeJS.ProcessEnv));
    expect(getDemoConfig(emptyDemo as NodeJS.ProcessEnv).enabled).toBe(false);
    expect(getDemoAiProviders(emptyDemo as NodeJS.ProcessEnv)).toBeUndefined();
    expect(getDemoAiTimeoutMs(emptyDemo as NodeJS.ProcessEnv)).toBe(45_000);
    expect(getDemoConfig(composeDefault as NodeJS.ProcessEnv).enabled).toBe(false);
  });

  const production = {
    NODE_ENV: 'production',
    JWT_ACCESS_SECRET: 'a'.repeat(48),
    JWT_REFRESH_SECRET: 'b'.repeat(48),
    MONGODB_URI: 'mongodb://user:s3cr3tpass@mongo:27017/mockia?authSource=admin',
    CORS_ORIGIN: 'https://app.example.com',
    APP_URL: 'https://app.example.com',
  } as NodeJS.ProcessEnv;

  it('production boots with the demo off and the secret empty', () => {
    expect(() => assertProdConfig({ ...production, ...composeDefault })).not.toThrow();
    expect(() => assertProdConfig({ ...production, ...emptyDemo })).not.toThrow();
  });

  it('production refuses to boot with the demo ON and the secret empty or short (and never echoes it)', () => {
    expect(() => assertProdConfig({ ...production, ...emptyDemo, DEMO_ENABLED: 'true' })).toThrow(/DEMO_HMAC_SECRET/);
    expect(() => assertProdConfig({ ...production, ...emptyDemo, DEMO_ENABLED: 'true', DEMO_HMAC_SECRET: 'short-secret' })).toThrow(/DEMO_HMAC_SECRET/);
    try {
      assertProdConfig({ ...production, ...emptyDemo, DEMO_ENABLED: 'true', DEMO_HMAC_SECRET: 'short-secret' });
    } catch (err) {
      expect(String(err)).not.toContain('short-secret');
    }
    expect(() => assertProdConfig({ ...production, ...emptyDemo, DEMO_ENABLED: 'true', DEMO_HMAC_SECRET: 'z'.repeat(44) })).not.toThrow();
  });
});
