/**
 * Mock API Types
 */

export interface MockAPI {
  id: string;
  name: string;
  description?: string;
  baseUrl: string;
  endpoints: MockEndpoint[];
  createdAt: string;
  updatedAt: string;
}

export interface MockEndpoint {
  id: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  path: string;
  responseSchema: Record<string, any>;
  statusCode: number;
}

export interface CreateMockAPIRequest {
  name: string;
  description?: string;
  baseUrl: string;
}

/**
 * Mock API Output - Generated by AI Service
 * Structure of the mock API specification generated by OpenRouter
 */
export interface MockAPIOutput {
  apiVersion: string;
  title: string;
  description: string;
  endpoints: Array<{
    path: string;
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
    description: string;
    requestSchema: Record<string, unknown>;
    responseSchema: Record<string, unknown>;
    examples: Array<{
      request: Record<string, unknown>;
      response: Record<string, unknown>;
    }>;
  }>;
  dataModels: Array<{
    name: string;
    schema: Record<string, unknown>;
  }>;
}
